
#[CONFIGMAP-SECRET]
#1_department-service_[ConfigMap-Secret].yml

apiVersion: v1
kind: ConfigMap
metadata:
  name: department-service
  namespace: default
data:
  #-------------------------------------------------------------------#
  #---------- CONFIGURACION PROPERTIES [department-service] ----------#
  #-------------------------------------------------------------------#
  application.properties: |-
    grupoconfig01.nombres=CESAR GUERRA
    grupoconfig01.dni=41816133
    propiedades.config.valor_01=JAVAMAN
    propiedades.config.valor_02=MAKTUP
    ingress.dns.employee=http://capacitacion.microservicios.employee
    ingress.dns.department=http://capacitacion.microservicios.department
    ingress.dns.organization=http://capacitacion.microservicios.organization

---

apiVersion: v1
kind: Secret
metadata:
  name: department-service-secret
  namespace: default
  #-------------------------------------------------------------------#
  #---------------------- CONFIGURACION SECRETs ----------------------#
  #--------- Formato BASE64 (https://www.base64encode.net/) ----------#
  #-------------------------------------------------------------------#
data:
  BOOTADMIN_USUARIO: YWRtaW4=
  BOOTADMIN_PASSWORD: YWRtaW4=

